# vi: set et ts=2 sw=2 :
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: install dependencies
      run: |
        sudo apt install \
          libjson-c-dev \
          cmake \
          gcc \
          git \
          make \
    - uses: actions/checkout@v2
    - name: cmake
      run: mkdir build && cd build && cmake ..
    - name: make
      run: make -C build

  macos-catalina:
    runs-on: macos-10.15

    steps:
    - name: install dependencies
      run: brew install cmake json-c
    - uses: actions/checkout@v2
    - name: cmake
      run: mkdir build && cd build && cmake ..
    - name: make
      run: make -C build

  win-srv-2019:

    runs-on: windows-2019

    steps:
    - name: install dependencies
      run: |-
        choco install cygwin -y
        choco install cyg-get -y
        # Line continuation in PowerShell is backtick. Weird as Windows.
        cyg-get gcc-g++ `
                cmake `
                make `
                libjson-c-devel `
                dos2unix
        echo "C:/tools/cygwin/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:/tools/cygwin/usr/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - uses: actions/checkout@v2
    - name: cmake
      run: bash -c "mkdir build && cd build && cmake .."
    - name: make
      run: make -C build
